### ISSUE TITLE
Suggestion: Config File Changes

### ISSUE THREAD

**Issue by rxay579** [The-Architects727/BiggerEndCities#1]
The default generated config file is a bit hard to read and configuration options are akward.
I'd suggest concise keys and values with longer descriptions added separately.

The default config file generates as:
Maximum Depth=8 #Higher means more Junctions | default: 8
Maximum Ships=1 #Best value is 10 to allow for many ships | default: 1
Maximum Middle Towers in a stack=2 #Best Value is 3-6 | default: 2
Bridge Lengths choose between: short, medium, long=short #Best for large cities is medium | default: short
Prioratize Branching. setting this to true will make more branches occur. can cause more overlap. Best is true=false # | default: false
More Loot Rooms. this will make more 3 layer buildings spawn. this will also make the cities much taller. Best is true=false # | default: false

Perhaps the config file could be adjusted such as:
# Max Depth, Default: 8. Higher means more junctions.
MAX_DEPTH=8
# Max Ships, Default: 2. Maximum number of ships generated.
MAX_SHIPS=2
# Max Fat Towers, Default 4. Maximum number of middle towers in a stack.
MAX_FAT_TOWERS=4
# Bridge Length, Default short. Options: short, medium, long. Length of bridges.
BRIDGE_LENGTH=short
# More Branches, Default false. Prioritize branching. Setting this to true will make more branches occur. Can cause more overlap.
MORE_BRANCHES=false
# More Loot Rooms, Default false. This will make more three layer buildings spawn. This will also make the cities much taller.
MORE_LOOT_ROOMS=false

**Comment by The-Architects727** [comment]
I have cleaned up the config as of the latest release.
