### ISSUE TITLE
The-Architects727 vs TheArchitects777

### ISSUE THREAD

**Issue by allanonmage** [The-Architects727/BiggerEndCities#2]
I came across your mods on Modrinth, which linked to some datapacks on Curseforge.  I noticed that your name is similar to the name of the dev on Curseforge.  Are you related or separate?  Please explain.

In building out my modpack for my server, I keep track of dev names and/or pack names, and select mods from devs that do a lot of work, with the presumption that if they have several mods they are more likely to continue to support the mods.  So if you're making mods and datapacks, that's great and improves your ranking in my spreadsheet.  If you two aren't related, that's OK too, but I'm just curious as to why your names are very similar.

**Comment by The-Architects727** [comment]
Both of those profiles are me. I think the reason why this one is 727 is because a while back I made a 777 on GitHub but lost access to it so had to change the numbers a bit.
