### ISSUE TITLE
Config doesn't load

### ISSUE THREAD

**Issue by Boba194230** [The-Architects727/BiggerEndCities#5]
I get an error that the config doesn't load. Already deleted and had it create a new one but after deleting it threw the same error up in the console.

[05:25:40] [main/ERROR] (SimpleConfig) Config 'bigendcitiesmodconfig' failed to load!
 
On fabric 1.20.1

**Comment by The-Architects727** [comment]
The issue has been fixed as of the latest version(1.0.4)

**Comment by Boba194230** [comment]
Sweet thanks
