### ISSUE TITLE
Crash in 1.20.4

### ISSUE THREAD

**Issue by Groupix05** [The-Architects727/BiggerEndCities#6]
The mod loads correctly and everything works except generating an end city
Sometimes it works.
https://mclo.gs/tN5JKRU

I really want to play with this mod but I can only play in 1.20.4, because I want to play with Geyser.

**Comment by The-Architects727** [comment]
I have Updated the mod on modrinth and curseforge, though the curseforge uploads need approval.

**Comment by Groupix05** [comment]
Yup, bug fixed in 1.20.4
No more crashes (except when config is too high)
